# Default values for chart

service:
  type: ClusterIP
  port: 3009

deploy:
  name: data-api
  replicas: 1
  acrServer: "fernando31300.eastus.cloudapp.azure.com"
  imageTag: "1.0"
  containerPort: 3009
